"""empty message

Revision ID: 65fbc15181b9
Revises: 6be8d8ec9d0c
Create Date: 2021-01-15 17:03:39.196968

"""
#  Copyright (c) 2018-2021 Beijing Ekitech Co., Ltd.
#  All rights reserved.

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '65fbc15181b9'
down_revision = '6be8d8ec9d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genetic_omim', sa.Column('pubmed', sa.Text(), nullable=True))
    op.execute("""alter table summary alter column major_allele type text;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genetic_omim', 'pubmed')
    # ### end Alembic commands ###
