"""empty message

Revision ID: 6be8d8ec9d0c
Revises: e916fef41725
Create Date: 2020-10-07 17:06:45.541651

"""
#  Copyright (c) 2018-2021 Beijing Ekitech Co., Ltd.
#  All rights reserved.

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6be8d8ec9d0c'
down_revision = 'e916fef41725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_related_macular_degeneration',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('corneal',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('corneal_endothelial_cells',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('keratoconus',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('macula',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('non_macula',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('retina',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('retina_macula',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('retina_non_macula',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('retinoblastoma',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('contrast_gene', sa.String(length=32), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('gene_network_gene')
    op.drop_table('tissue_network_gene')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tissue_network_gene',
                    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('gene', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
                    sa.Column('contrast_gene', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
                    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('tissue', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='tissue_network_gene_pkey')
                    )
    op.create_table('gene_network_gene',
                    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('gene', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
                    sa.Column('contrast_gene', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
                    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('disease', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='gene_network_gene_pkey')
                    )
    op.drop_table('retinoblastoma')
    op.drop_table('retina_non_macula')
    op.drop_table('retina_macula')
    op.drop_table('retina')
    op.drop_table('non_macula')
    op.drop_table('macula')
    op.drop_table('keratoconus')
    op.drop_table('corneal_endothelial_cells')
    op.drop_table('corneal')
    op.drop_table('age_related_macular_degeneration')
    # ### end Alembic commands ###
