"""empty message

Revision ID: e916fef41725
Revises: bc246dea3bfe
Create Date: 2020-09-24 14:35:46.900289

"""
#  Copyright (c) 2018-2021 Beijing Ekitech Co., Ltd.
#  All rights reserved.

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e916fef41725'
down_revision = 'bc246dea3bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_disease_correct',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('module', sa.String(length=32), nullable=True),
                    sa.Column('kme', sa.Float(), nullable=True),
                    sa.Column('disease', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('gene_tissue_correct',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('gene', sa.String(length=32), nullable=True),
                    sa.Column('module', sa.String(length=32), nullable=True),
                    sa.Column('kme', sa.String(length=32), nullable=True),
                    sa.Column('tissue', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('gene_network_gene', sa.Column('disease', sa.String(length=64), nullable=True))
    op.add_column('tissue_network_gene', sa.Column('tissue', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tissue_network_gene', 'tissue')
    op.drop_column('gene_network_gene', 'disease')
    op.drop_table('gene_tissue_correct')
    op.drop_table('gene_disease_correct')
    # ### end Alembic commands ###
